### PR TITLE
Footer, Logo, Slider and some basic layout changes

### PR DESCRIPTION
**Pull request by nikeshbalami**
Hi @garethrees, We had made few changes to make AskNepal clean and user-friendly by removing previously added footer section and some stuff. This year we are planning to take AskNepal in a full swing and we would definitely need lots of your help.

Please help us to review and merge this pull request, thanks in advance.

### CODE REVIEW

**Comment by garethrees** [comment]
Cool! We'll get this reviewed, merged and deployed as soon as we can over the next week or so.

**Comment by nikeshbalami** [comment]
Thanks Gareth, If possible let's merge and deploy it within this week.

**Comment by nikeshbalami** [comment]
And while making a change, please help by making English the default language and Nepali the secondary language. There is some Typo error in the translation, will work soon to improve the quality of the Nepali Translation.

**Comment by garethrees** [comment]
Made some fixes and merged as 258c8610e66eaf847958a190255919270282be97 and 5f7958a35959465c5034d7a9b20df31267bacbcf.

> And while making a change, please help by making English the default language and Nepali the secondary language. There is some Typo error in the translation, will work soon to improve the quality of the Nepali Translation.

Sorry – this is going to be too difficult to do at the moment. There's some manual work involved in switching the default locale which we don't have capacity for at the moment. Do let us know when you've made substantial updates to the Nepali translation though – we can certainly get that updated fairly easily.

**Comment by nikeshbalami** [comment]
Thanks @garethrees, this is great 👍

**Pull request closed without merging**
